// Code generated by goctl. DO NOT EDIT!
// Source: comment.proto

//go:generate mockgen -destination ./comment_mock.go -package commentclient -source $GOFILE

package commentclient

import (
	"context"

	"zerotest/comment/rpc/comment"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	IdRequest       = comment.IdRequest
	CommentResponse = comment.CommentResponse

	Comment interface {
		GetComment(ctx context.Context, in *IdRequest) (*CommentResponse, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

func (m *defaultComment) GetComment(ctx context.Context, in *IdRequest) (*CommentResponse, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.GetComment(ctx, in)
}
