// Code generated by goctl. DO NOT EDIT!
// Source: comment.proto

package server

import (
	"context"

	"zerotest/comment/rpc/comment"
	"zerotest/comment/rpc/internal/logic"
	"zerotest/comment/rpc/internal/svc"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) GetUser(ctx context.Context, in *comment.IdRequest) (*comment.CommentResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
